[package]
name = "reciprocity_bot"
version = "0.1.0"
authors = ["Autumnal <friedrich122112@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "^0.5.2"
log = "^0.4.14"
futures = "^0.3.13"
smol =  "^1.2.5"
arc-swap = "^1.2.0"
async-compat = "^0.2.0"
anyhow = "^1.0.38"
thiserror = "^1.0.24"
serde_json = "^1.0.64"
serde_yaml = "^0.8.17"
serde = { version = "^1.0", features = ["derive"] }
arraydeque = "^0.4.5"
event-listener = "^2.5.1"
easy-parallel = "^3.1.0"

serenity = { version = "^0.10.2", default-features = false, features = ["client", "gateway", "model", "rustls_backend", "voice", "extras", "collector"]}
songbird = { version = "^0.1.3", default-features = false, features = ["serenity-rustls", "gateway"]}
lavalink-rs = {git = "https://gitlab.com/nitsuga5124/lavalink-rs", branch = "master", features = ["serenity", "rustls"]}