[package]
name = "reciprocity_bot"
version = "0.1.0"
authors = ["Autumnal <friedrich122112@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.5.2"
futures = "0.3.8"
tokio = { version = "0.3.3", features = ["full"] }

serenity = "0.9.1"
