[package]
name = "reciprocity_bot"
version = "0.1.0"
authors = ["Autumnal <friedrich122112@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "^0.5.2"
log = "^0.4.11"
futures = "^0.3.8"
tokio = { version = "^0.3.3", features = ["full"] }
async-std = "^1.7.0"
arc-swap = "1.0.0"

serenity = { version = "^0.9.1", default-features = false, features = ["client", "gateway", "model", "rustls_backend"]}
songbird = {git = "https://github.com/serenity-rs/songbird", branch = "current", features = ["serenity-native", "gateway"]}
lavalink-rs = {git = "https://gitlab.com/nitsuga5124/lavalink-rs", branch = "songbird"}